### ISSUE TITLE
Elasticsearch 1.4.0 hangs on running twitter river

### ISSUE THREAD

**Issue by Vineeth-Mohan** [elasticsearch/elasticsearch-river-twitter#83]
Elasticsearch version - 1.4.0
River version - 2.4.1
Symptom - curl 'http://148.163.87.7:9200/_cluster/state' hangs

Strangely this works well in my dev environment but not production.

**Comment by Jenny-discussit** [comment]
I think were having the same issue, anyone found anything out about it?

**Comment by dadoonet** [comment]
@Vineeth-Mohan Did you try to upgrade to 1.4.2? The first tests I'm running (JUnit tests) seem to pass on 1.4.3-SNAPSHOT which is close to 1.4.2.

**Comment by Jenny-discussit** [comment]
1.4.2 doesn't seam to work. maybe they have fixed it in 1.4.3

**Comment by dadoonet** [comment]
That's super weird. I tested this on 1.4.0 and 1.4.2 (also dev machine and can not reproduce it).

Here is what I did:

* install elasticsearch 1.4.0 (and 1.4.2) 
* `bin/plugin -install elasticsearch/elasticsearch-river-twitter/2.4.1`
* modify `config/elasticsearch.yml`:
```
river:
      twitter:
          oauth:
             consumer_key: ""
             consumer_secret: ""
             access_token: ""
             access_token_secret: ""
```
* launch `bin/elasticsearch`
* create the river: `curl -XPUT localhost:9200/_river/my_twitter_river/_meta -d '{ "type" : "twitter" }'`
* call cluster api: `curl localhost:9200/_cluster/state?pretty`

Everything works well on both versions. I don't understand what could happen here.

For you guys who are hitting this issue, could you tell me more about your infra. Are you running on `ec2` on premise or other cloud provider? 
Could you turn on trace in `config/logging.yml` and attach the result?

Thanks for your help!
